default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20

development:
  <<: *default
  database: blackjack-rails-api_development
  host: localhost

test:
  <<: *default
  database: blackjack-rails-api_test
  host: localhost

production:
  url: <%= ENV['DATABASE_URL'] %>
